services:
  web-app:
    build:
      context: ./web-app
    container_name: web-app
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGO_URI}
    env_file:
      - .env
    command: ["pipenv", "run", "python", "web_app.py"]

  ml-client:
    build:
      context: ./machine-learning-client
    container_name: ml-client
    environment:
      - MONGO_URI=${MONGO_URI}
    env_file:
      - .env
    command: ["pipenv", "run", "python", "app.py"]

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
