services:
  web-app:
    build:
      context: ./web_app
    container_name: web-app
    ports:
      - "5001:5001"
    env_file:
      - .env
    depends_on:
      - mongodb
    command: ["pipenv", "run", "python", "web_app.py"]

  ml-client:
    build:
      context: ./machine-learning-client
    container_name: ml-client
    env_file:
      - .env
    depends_on:
      - mongodb
    command: ["pipenv", "run", "python", "app.py"]

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
